youtube = [
    "channel/UCoSrY_IQQVpmIRZ9Xf-y93g", # Gawr, Gura
    "channel/UCIdEIHpS0TdkqRkHL5OkLtA", # Natori, Sana
    "channel/UCNsidkYpIAQ4QaufptQBPHQ", # Weather News
]

niconico = [
    "co3782975", # teguru
    "co1989588", # Seris
    "co4043409", # Imagawa
]